version: '2.27.1-desktop.1'
services:
  backend:
    image: demorestapi:backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8082"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SERVER_PORT = 8082
      - SPRING_DATASOURCE_URL = jdbc:postgresql://database/postgres

  database:
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_USER: client
      POSTGRES_PASSWORD: password
    ports:
      - "8081:5432"
    volumes:
      - .C:\Users\pilig\IdeaProjects\demoRestApi\src\main\resources\database\initDB.sql
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db-data: